apiVersion: v1
kind: Secret
metadata:  
  name: mysql-pass
  namespace: kojiki
type: Opaque
data:
  username: d29yZHByZXNz
  password: I1haU0F3cTIxIw==
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: kojiki
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
    tier: frontend
  type: NodePort
  #type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  namespace: kojiki
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: kojiki
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: wordpress:latest
        name: wordpress
        env:
        - name: WORDPRESS_CONFIG_EXTRA
          value: define('MYSQL_CLIENT_FLAGS', MYSQLI_CLIENT_SSL);         
        - name: WORDPRESS_DB_HOST
          value: kojiki-mysqldb.mysql.database.azure.com
        - name: WORDPRESS_DB_USER
          value: wordpress
        - name: WORDPRESS_DB_NAME
          value: wordpress
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim
#---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: wordpress
#  namespace: kojiki
#  annotations:
#    kubernetes.io/ingress.class: azure/application-gateway
#    cert-manager.io/cluster-issuer: letsencrypt
#    cert-manager.io/acme-challenge-type: http01
#spec:
#  rules:
#  - host: w3-int.kojiki.eu
#    http:
#      paths:
#      - path: /
#        pathType: Prefix
#        backend:
#          service:
#            name: wordpress
#            port:
#              number: 80
#  tls:
#  - hosts:
#    - w3-int.kojiki.eu
#    secretName: wp-secret-name